Jobfinding/Models/Findjobs.cs
using Jobfinding.Data.Base;
using Jobfinding.Data.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Jobfinding.Models
{
    public class Findjobs:IEntityBase
    { 

        [Key]
        public int Id { get; set; }
        public String Name { get; set; }
        public String Description { get; set; }
        public double Salary { get; set; }
        public string ImageURL { get; set; }

        public DateTime Startdate { get; set; }
        public DateTime Enddate { get; set; }
        public JobCategory JobCategory { get; set;}
        //rel
        public List<skills_findingjobs> skills_Findingjobs { get; set; }

        public List<question_ans> question_ans{ get; set; }

        //job

        public int JobsId { get; set; }
        [ForeignKey("JobsId")] 
        public Jobs Jobs { get; set; }

        public int CompanyId { get; set; }
        [ForeignKey("CompanyId")]
        public Company Company { get; set; }



    }
}

Jobfinding/Controllers/ApplysController.cs
using Jobfinding.Data.Cart;
using Jobfinding.Data.Services;
using Jobfinding.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Jobfinding.Controllers
{

    public class ApplysController : Controller
    {
        private readonly IFindjobsServices _findjobsService;
        private readonly ApplyCart _applyCart;
        private readonly IApplysService _applysService;


        public ApplysController(IFindjobsServices findjobsService, ApplyCart applyCart, IApplysService applysService)
        {
            _findjobsService = findjobsService;
            _applyCart = applyCart;
            _applysService = applysService;
        }

        public IActionResult ApplyCart()
        {
            var items = _applyCart.GetApplyCartItems();
            _applyCart.ApplyCartItems = items;

            var response = new ApplyCartVM()
            {
                ApplyCart = _applyCart,
                ApplyCartTotal = _applyCart.GetApplyCartTotal()
            };
            return View(response);
        }
        public async Task<IActionResult> AddItemToApplyCart(int id)
        {
            var item = await _findjobsService.GetFindjobsByIdAsync(id);

            if (item != null)
            {
                _applyCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ApplyCart));
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var applys = await _applysService.GetApplysByUserIdAndRoleAsync(userId,userRole);
            return View(applys);
        }


        public async Task<IActionResult> RemoveItemFromApplyCart(int id)
        {
            var item = await _findjobsService.GetFindjobsByIdAsync(id);

            if (item != null)
            {
                _applyCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ApplyCart));
        }
        public async Task<IActionResult> CompleteApply()
        {
            var items = _applyCart.GetApplyCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _applysService.StoreApplyAsync(items, userId, userEmailAddress);
            await _applyCart.ClearApplyCartAsync();

            return View("ApplyCompleted");
        }


    }

}

Jobfinding/Controllers/FindjobsController.cs
using Jobfinding.Data;
using Jobfinding.Data.Services;
using Jobfinding.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Jobfinding.Controllers
{
    public class FindjobsController : Controller
    {
        private readonly IFindjobsServices _service;
        public FindjobsController(IFindjobsServices service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync(n =>n.Jobs);
            return View(data);
        }
        //filter
        public async Task<IActionResult> Filter(string searchString)
        {
            var data = await _service.GetAllAsync(n => n.Jobs);
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = data.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString) || n.JobCategory.ToString().Contains(searchString)).ToList();

                return View("Index",filteredResult);
            }
            return View("Index",data);
        }
        //create
        public async  Task<IActionResult> Create()
        {
            var data = await _service.GetNewFindjobsDropDownValues();
            ViewBag.Jobs = new SelectList(data.Jobs, "Id", "Name");
            ViewBag.Companys = new SelectList(data.Companys, "Id", "Name");
            ViewBag.Skills = new SelectList(data.Skills, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create( NewFindjobsVM jobs)
        {
            if (!ModelState.IsValid)
            {
                var data = await _service.GetNewFindjobsDropDownValues();
                ViewBag.Jobs = new SelectList(data.Jobs, "Id", "Name");
                ViewBag.Companys = new SelectList(data.Companys, "Id", "Name");
                ViewBag.Skills = new SelectList(data.Skills, "Id", "Name");
                return View();
                return View(jobs);
            } 
            await _service.AddNewFIndjobsAsync(jobs);
            return RedirectToAction(nameof(Index));

        }

        //Edit
        public async Task<IActionResult> Edit(int id)
        {
            var findjobsDetails = await _service.GetFindjobsByIdAsync(id);
            if (findjobsDetails == null) return View("NotFound");

            var response = new NewFindjobsVM()
            {
                Id = findjobsDetails.Id,
                Name = findjobsDetails.Name,
                Description = findjobsDetails.Description,
                Salary = findjobsDetails.Salary,
                Startdate=findjobsDetails.Startdate,
                Enddate=findjobsDetails.Enddate,
                ImageURL = findjobsDetails.ImageURL,
                JobCategory = findjobsDetails.JobCategory,
                JobsId = findjobsDetails.JobsId,
                CompanyId = findjobsDetails.CompanyId,
                SkillIds = findjobsDetails.skills_Findingjobs.Select(n => n.SkillId).ToList(),

            };
            var data = await _service.GetNewFindjobsDropDownValues();
            ViewBag.Jobs = new SelectList(data.Jobs, "Id", "Name");
            ViewBag.Companys = new SelectList(data.Companys, "Id", "Name");
            ViewBag.Skills = new SelectList(data.Skills, "Id", "Name");
            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,NewFindjobsVM jobs)
        {
            if (id != jobs.Id) return View("NotFound");
            if (!ModelState.IsValid)
            {
                var data = await _service.GetNewFindjobsDropDownValues();
                ViewBag.Jobs = new SelectList(data.Jobs, "Id", "Name");
                ViewBag.Companys = new SelectList(data.Companys, "Id", "Name");
                ViewBag.Skills = new SelectList(data.Skills, "Id", "Name");
                return View();
                return View(jobs);
            }
            await _service.UpdateFIndjobsAsync(jobs);
            return RedirectToAction(nameof(Index));

        }

        //detail
        public async Task<IActionResult> Details(int id)
        {
            var jobsDetails = await _service.GetFindjobsByIdAsync(id);

            return View(jobsDetails);
        }
       
        //delete
        public async Task<IActionResult> Delete(int id)
        {
            var jobsDetails = await _service.GetByIdAsync(id);

            if (jobsDetails == null) return View("NotFound");

            return View(jobsDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jobsDetails = await _service.GetByIdAsync(id);

            if (jobsDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));

        }

    }
}

Jobfinding/Controllers/JobsController.cs
using Jobfinding.Data;
using Jobfinding.Data.Services;
using Jobfinding.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Jobfinding.Controllers
{
    public class JobsController : Controller
    {
        private readonly IJobsService _service;
        public JobsController(IJobsService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        //create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,ImageURL,Info")] Jobs jobs)
        {
            if (ModelState.IsValid)
            {
                return View(jobs);
            }
            await _service.AddAsync(jobs);
            return RedirectToAction(nameof(Index));

        }
        //detail
        public async Task<IActionResult> Details(int id)
        {
            var jobsDetails = await _service.GetByIdAsync(id);

            if (jobsDetails == null) return View("NotFound");
            return View(jobsDetails);
        }
        //Edit
        public async Task<IActionResult> Edit(int id)
        {
            var jobsDetails = await _service.GetByIdAsync(id);

            if (jobsDetails == null) return View("NotFound");

            return View(jobsDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ImageURL,Info")] Jobs jobs)
        {
            if (ModelState.IsValid)
            {
                return View(jobs);
            }
            await _service.UpdateAsync(id, jobs);
            return RedirectToAction(nameof(Index));

        }
        //delete
        public async Task<IActionResult> Delete(int id)
        {
            var jobsDetails = await _service.GetByIdAsync(id);

            if (jobsDetails == null) return View("NotFound");

            return View(jobsDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jobsDetails = await _service.GetByIdAsync(id);

            if (jobsDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);

            return RedirectToAction(nameof(Index));

        }

    }
}

Jobfinding/Controllers/SkillController.cs
using Jobfinding.Data;
using Jobfinding.Data.Services;
using Jobfinding.Models;
using Microsoft.AspNetCore.Mvc;

namespace Jobfinding.Controllers
{
    public class SkillController : Controller
    {
        private readonly ISkillService _service;
        public SkillController(ISkillService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
             var data =await _service.GetAllAsync(); 
            return View(data);
        }
        //create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost] 
        public async Task<IActionResult> Create([Bind("Name,ImageURL,Info")]Skill skill)
        {
            if(ModelState.IsValid)
            {
                return View(skill);
            }
            await _service.AddAsync(skill);
            return RedirectToAction(nameof(Index));

        }
        //detail
        public async Task<IActionResult> Details(int id)
        {
            var skillDetails =await _service.GetByIdAsync(id);

            if (skillDetails == null) return View("NotFound");
            return View(skillDetails);
        }
        //Edit
        public async Task<IActionResult> Edit(int id)
        {
            var skillDetails = await _service.GetByIdAsync(id);

            if (skillDetails == null) return View("NotFound");

            return View(skillDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,Name,ImageURL,Info")] Skill skill)
        {
            if (ModelState.IsValid)
            {
                return View(skill);
            }
            await _service.UpdateAsync(id,skill);
            return RedirectToAction(nameof(Index));

        }
        //delete
        public async Task<IActionResult> Delete(int id)
        {
            var skillDetails = await _service.GetByIdAsync(id);

            if (skillDetails == null) return View("NotFound");

            return View(skillDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var skillDetails = await _service.GetByIdAsync(id);

            if (skillDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);
           
            return RedirectToAction(nameof(Index));

        }

    }
}
 

Jobfinding/Views/Findjobs/Create.cshtml
@model NewFindjobsVM
@using Jobfinding.Data;
@using Jobfinding.Data.Enums;

@{
    ViewData["Title"] = "Create a New Requirement";
}

<style>
    .form-container {
        padding: 20px;
        background-color: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 5px;
    }

    .form-title {
        margin-bottom: 20px;
        font-size: 24px;
        font-weight: 600;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-label {
        font-weight: 500;
    }

    .form-control {
        height: 40px;
    }

    .img-preview-container {
        margin-top: 20px;
    }

    .img-preview {
        max-width: 100%;
        height: auto;
    }

    .btn-create {
        background-color: #28a745;
        color: #fff;
    }

    .btn-show-all {
        background-color: #6c757d;
        color: #fff;
    }
</style>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <div class="form-container">
            <h4 class="form-title">Create a New Requirement</h4>

            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Name" class="form-label">Requirement Name</label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Startdate" class="form-label">Start Date</label>
                            <input asp-for="Startdate" type="date" class="form-control" />
                            <span asp-validation-for="Startdate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Enddate" class="form-label">End Date</label>
                            <input asp-for="Enddate" type="date" class="form-control" />
                            <span asp-validation-for="Enddate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Salary" class="form-label">Salary</label>
                            <input asp-for="Salary" type="number" class="form-control" />
                            <span asp-validation-for="Salary" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ImageURL" class="form-label">Image URL</label>
                            <input asp-for="ImageURL" class="form-control" />
                            <span asp-validation-for="ImageURL" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="JobsId" class="form-label">Job ID</label>
                            <select asp-for="JobsId" class="form-control" asp-items="ViewBag.Jobs"></select>
                            <span asp-validation-for="JobsId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="JobCategory" class="form-label">Job Category</label>
                            <select asp-for="JobCategory" class="form-control" asp-items="Html.GetEnumSelectList<JobCategory>()"></select>
                            <span asp-validation-for="JobCategory" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CompanyId" class="form-label">Company ID</label>
                            <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.Companys"></select>
                            <span asp-validation-for="CompanyId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SkillIds" class="form-label">Skills</label>
                            <select asp-for="SkillIds" class="form-control" asp-items="ViewBag.Skills" multiple></select>
                            <span asp-validation-for="SkillIds" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label asp-for="Description" class="form-label">Description</label>
                            <textarea asp-for="Description" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                </div>

                <div class="img-preview-container">
                    <label class="form-label">Image Preview</label>
                    <div class="text-center">
                        <img id="ImageUrlPreview" class="img-preview" />
                    </div>
                </div>

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-create float-right" />
                    <a class="btn btn-show-all" asp-action="Index">Show All</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        });
    </script>
}

Jobfinding/Views/Findjobs/Details.cshtml
@model Findjobs
@{
    ViewData["Title"] = "Jobs details";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" integrity="sha512-LUhLzcnVEZh7D2p6XeAmXSyZjtCwCu4aY3Q4T/yvGxNNRSH9fJ6o9np5Xnpgv09Zr6aOaWnRZDJz/Z94W4ip1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        .smaller-image {
            max-width: 200px; /* Adjust the value as per your preference */
            height: auto;
        }

        .card {
            padding: 1.5rem;
        }

        .card-footer {
            padding: 1.5rem;
        }

        .vertical-center {
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
</head>
<body>
    <div class="row">
        <div class="col-md-8 offset-2">
            <div class="card mb-12">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @Model.Name
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-4 vertical-center">
                        <img src="@Model.ImageURL" class="img-fluid smaller-image" alt="@Model.Name">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text">@Model.Description</p>
                            <div class="row">
                                <div class="col-md-6">
                                    <p class="card-text">
                                        <b>Job: </b>
                                        <a asp-controller="Jobs" asp-action="Details" asp-route-id="@Model.JobsId">
                                            @Model.Jobs.Name
                                        </a>
                                    </p>
                                    <p class="card-text"><b>Category: </b>@Model.JobCategory</p>
                                    <p class="card-text"><b>Salary: </b>@Model.Salary.ToString("c")</p>
                                </div>
                                <div class="col-md-6">
                                    <p class="card-text"><b>Start Date: </b>@Model.Startdate.ToString("dd MMM yy")</p>
                                    <p class="card-text"><b>End Date: </b>@Model.Enddate.ToString("dd MMM yy")</p>
                                    <p class="card-text">
                                        <b>Status: </b>
                                        @if (DateTime.Now >= Model.Startdate && DateTime.Now <= Model.Enddate)
                                        {
                                            <span class="badge bg-success text-white">AVAILABLE</span>
                                        }
                                        else if (DateTime.Now > Model.Enddate)
                                        {
                                            <span class="badge bg-danger text-white">EXPIRED</span>
                                        }
                                        else
                                        {
                                            <span class="badge bg-primary text-white">UPCOMING</span>
                                        }
                                    </p>
                                </div>
                            </div>
                            <p class="card-text">
                                <b>Skills: </b>
                                <hr />
                                <div class="row">
                                    @foreach (var skill in Model.skills_Findingjobs)
                                    {
                                        <div class="col-md-3">
                                            <img src="@skill.Skill.ImageURL" style="max-width: 100%;" />
                                            <br />
                                            <a asp-controller="Skill" asp-action="Details" asp-route-id="@skill.SkillId">@skill.Skill.Name</a>
                                        </div>
                                    }
                                </div>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Index">
                                    Back to List
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > Model.Enddate) ? "disabled" : "")"
                                   asp-controller="Applys"
                                   asp-action="AddItemToApplyCart" asp-route-id="@Model.Id"> Apply Fee @((Model.Salary/10).ToString("c"))</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/js/bootstrap.bundle.min.js" integrity="sha512-p4PhTw5JNKdmmN82S6feoLbmkJsHt9MTJLeb2bA9g6bL1RnKY3QWdxK0Z7u8IN6dFUhUe5KOkT+HTPTyDWU7GQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>

Jobfinding/Views/Findjobs/Index.cshtml
@model IEnumerable<Findjobs>

@{
    ViewData["Title"] = "List of Current Jobs";
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" integrity="sha512-LUhLzcnVEZh7D2p6XeAmXSyZjtCwCu4aY3Q4T/yvGxNNRSH9fJ6o9np5Xnpgv09Zr6aOaWnRZDJz/Z94W4ip1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.5.0/font/bootstrap-icons.min.css" integrity="sha512-0xuwqbxqUS+GJZqm2yj/kSGKT4v7nBbjsnStUBjTqvmxrJ6azgvk+R5pvsVDFKd6SXlU1EmxklSD0bTWRtuBlw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        .job-card {
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s ease;
            border: none;
            border-radius: 10px;
            overflow: hidden;
        }

            .job-card:hover {
                box-shadow: 0 8px 12px rgba(0, 0, 0, 0.2);
            }

        .card-header {
            background-color: #f8f9fa;
            border-bottom: none;
            padding: 1.5rem;
        }

        .card-title {
            font-size: 1.2rem;
            font-weight: bold;
        }

        .card-body {
            padding: 1.5rem;
        }

        .card-text {
            margin-bottom: 0.5rem;
        }

        .badge {
            font-size: 0.8rem;
            padding: 0.4rem 0.6rem;
            border-radius: 2rem;
        }

        .btn-details {
            font-size: 0.9rem;
            padding: 0.5rem 1rem;
        }

        .btn-test {
            font-size: 0.9rem;
            padding: 0.5rem 1rem;
        }

        .container {
            max-width: 800px;
            margin-bottom: 50px;
        }

        .row.mb-3 {
            margin-bottom: 20px;
        }

    
        .job-card .col-md-4 {
            display: flex;
            flex-direction: column;
            justify-content: center;
        }

        .job-card img {
            display: block;
            margin: auto;
            max-height: 100px;
            max-width: 100px;
        }
    </style>
</head>
<body>
    <div class="container">
        @if (User.Identity.IsAuthenticated)
        {
            <div class="alert alert-primary mt-3" role="alert">
                Welcome, @Context.Session.GetString("UserName")!
            </div>
        }
        @foreach (var item in Model)
        {
            <div class="row mb-3">
                <div class="col-md-12">
                    <div class="card h-100 job-card">
                        <div class="card-header">
                            <h5 class="card-title d-flex justify-content-between align-items-center">
                                <span>@item.Name</span>
                                @if (User.Identity.IsAuthenticated && User.IsInRole("Employer"))
                                {
                                    <a class="text-decoration-none text-secondary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                }
                            </h5>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="@item.ImageURL" class="img-fluid" alt="@item.Name">
                                    <p class="card-text">@item.Description</p>
                                </div>
                                <div class="col-md-4">
                                    <p class="card-text"><b>Job: </b>@item.Jobs.Name</p>
                                    <p class="card-text"><b>Category: </b>@item.JobCategory</p>
                                    <p class="card-text"><b>Salary: </b>@item.Salary</p>
                                </div>
                                <div class="col-md-4">
                                    <p class="card-text"><b>Start Date: </b>@item.Startdate.ToString("dd MMM yy")</p>
                                    <p class="card-text"><b>End Date: </b>@item.Enddate.ToString("dd MMM yy")</p>
                                    <p class="card-text">
                                        <b>Status: </b>
                                        @if (DateTime.Now >= item.Startdate && DateTime.Now <= item.Enddate)
                                        {
                                            <span class="badge bg-success text-white">AVAILABLE</span>
                                        }
                                        else if (DateTime.Now > item.Enddate)
                                        {
                                            <span class="badge bg-danger text-white">EXPIRED</span>
                                        }
                                        else
                                        {
                                            <span class="badge bg-primary text-white">UPCOMING</span>
                                        }
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="d-flex justify-content-between align-items-center">
                                <a class="btn btn-outline-primary btn-details" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye-fill"></i> Show Details</a>
                                @if (User.Identity.IsAuthenticated && User.IsInRole("Seeker"))
                                {
                                    <a class="btn btn-danger btn-test @((DateTime.Now > item.Enddate) ? "disabled" : "")" asp-controller="Applys" asp-action="AddItemToApplyCart" asp-route-id="@item.Id">
                                        <i class="bi bi-question-circle"></i> Apply for Job
                                </a>}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

    <div class="container">
        @await Html.PartialAsync("_CreateItem", "Findjobs")
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.2/js/bootstrap.bundle.min.js" integrity="sha512-LOsdavpWDEZ94LmdBN6J1BgoT2nZSv0ijMO6sMo8bcQw5BfpmPBMbR9Oqnc68EFQF95ptT//kJW6Brqy/4ghZw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>